<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterPrice (low to high)</name>
   <tag></tag>
   <elementGuidId>e9708c58-4bdb-4a49-a7c8-906e08e04121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header_container']/div[2]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b545067-d269-44a6-b008-366cc24343ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select_container</value>
      <webElementGuid>83615d3c-00f7-40db-9b08-979320c0005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price (low to high)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)</value>
      <webElementGuid>a6f0c8b2-4e7e-4538-b43e-3d7b8b3fafdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_container&quot;)/div[@class=&quot;header_secondary_container&quot;]/div[@class=&quot;right_component&quot;]/span[@class=&quot;select_container&quot;]</value>
      <webElementGuid>89776746-2dd8-488f-97a2-c71f015cd706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header_container']/div[2]/div/span</value>
      <webElementGuid>5f1b95ac-0952-45af-ae0d-1a2b76dfba2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/span</value>
      <webElementGuid>775f5758-dee4-4119-b479-4b0548d8851f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Price (low to high)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)' or . = 'Price (low to high)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)')]</value>
      <webElementGuid>331af538-ff59-45bd-bc6d-a8bd426cc407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
